import { createSlice } from "@reduxjs/toolkit";

const INITIAL_EMPLOYEES = [
  {
    id: "EMP001",
    firstName: "Aria",
    lastName: "Chen",
    email: "aria.chen@staffhub.io",
    phone: "+1 (555) 201-3847",
    department: "Engineering",
    jobTitle: "Senior Frontend Developer",
    employmentType: "Full-time",
    reportingManager: "James Kim",
    workLocation: "San Francisco HQ",
    status: "Active",
    dateOfJoining: "2021-03-15",
    contractStart: "2021-03-15",
    contractEnd: "",
    probationEnd: "2021-06-15",
    salary: "$145,000",
    band: "L5",
    grade: "Senior",
    role: "Developer",
  },
  {
    id: "EMP002",
    firstName: "Marcus",
    lastName: "Webb",
    email: "marcus.webb@staffhub.io",
    phone: "+1 (555) 302-9183",
    department: "Product",
    jobTitle: "Product Manager",
    employmentType: "Full-time",
    reportingManager: "Sarah Okonkwo",
    workLocation: "New York Office",
    status: "Active",
    dateOfJoining: "2020-07-01",
    contractStart: "2020-07-01",
    contractEnd: "",
    probationEnd: "2020-10-01",
    salary: "$160,000",
    band: "L6",
    grade: "Lead",
    role: "Manager",
  },
  {
    id: "EMP003",
    firstName: "Priya",
    lastName: "Nair",
    email: "priya.nair@staffhub.io",
    phone: "+1 (555) 478-2019",
    department: "Design",
    jobTitle: "UI/UX Designer",
    employmentType: "Full-time",
    reportingManager: "Aria Chen",
    workLocation: "Remote",
    status: "Active",
    dateOfJoining: "2022-01-10",
    contractStart: "2022-01-10",
    contractEnd: "",
    probationEnd: "2022-04-10",
    salary: "$115,000",
    band: "L4",
    grade: "Mid",
    role: "Designer",
  },
  {
    id: "EMP004",
    firstName: "Daniel",
    lastName: "Torres",
    email: "d.torres@staffhub.io",
    phone: "+1 (555) 591-7342",
    department: "Engineering",
    jobTitle: "Backend Engineer",
    employmentType: "Contract",
    reportingManager: "James Kim",
    workLocation: "Austin Office",
    status: "On Leave",
    dateOfJoining: "2021-09-20",
    contractStart: "2023-01-01",
    contractEnd: "2024-12-31",
    probationEnd: "",
    salary: "$130,000",
    band: "L4",
    grade: "Mid",
    role: "Developer",
  },
  {
    id: "EMP005",
    firstName: "Sione",
    lastName: "Faleolo",
    email: "s.faleolo@staffhub.io",
    phone: "+1 (555) 603-8821",
    department: "HR",
    jobTitle: "HR Specialist",
    employmentType: "Full-time",
    reportingManager: "Lea Mori",
    workLocation: "San Francisco HQ",
    status: "Active",
    dateOfJoining: "2022-06-01",
    contractStart: "2022-06-01",
    contractEnd: "",
    probationEnd: "2022-09-01",
    salary: "$95,000",
    band: "L3",
    grade: "Junior",
    role: "HR",
  },
  {
    id: "EMP006",
    firstName: "Zoe",
    lastName: "Harper",
    email: "zoe.harper@staffhub.io",
    phone: "+1 (555) 714-2290",
    department: "Marketing",
    jobTitle: "Growth Analyst",
    employmentType: "Intern",
    reportingManager: "Marcus Webb",
    workLocation: "Remote",
    status: "Probation",
    dateOfJoining: "2024-02-01",
    contractStart: "2024-02-01",
    contractEnd: "2024-08-01",
    probationEnd: "2024-05-01",
    salary: "$48,000",
    band: "L1",
    grade: "Intern",
    role: "Analyst",
  },
  {
    id: "EMP007",
    firstName: "James",
    lastName: "Kim",
    email: "james.kim@staffhub.io",
    phone: "+1 (555) 825-4410",
    department: "Engineering",
    jobTitle: "Engineering Manager",
    employmentType: "Full-time",
    reportingManager: "CEO",
    workLocation: "San Francisco HQ",
    status: "Active",
    dateOfJoining: "2019-04-01",
    contractStart: "2019-04-01",
    contractEnd: "",
    probationEnd: "2019-07-01",
    salary: "$210,000",
    band: "L7",
    grade: "Principal",
    role: "Manager",
  },
  {
    id: "EMP008",
    firstName: "Lea",
    lastName: "Mori",
    email: "lea.mori@staffhub.io",
    phone: "+1 (555) 936-0038",
    department: "HR",
    jobTitle: "HR Director",
    employmentType: "Full-time",
    reportingManager: "CEO",
    workLocation: "New York Office",
    status: "Active",
    dateOfJoining: "2018-11-15",
    contractStart: "2018-11-15",
    contractEnd: "",
    probationEnd: "2019-02-15",
    salary: "$185,000",
    band: "L7",
    grade: "Director",
    role: "Admin",
  },
  {
    id: "EMP009",
    firstName: "Rohan",
    lastName: "Verma",
    email: "r.verma@staffhub.io",
    phone: "+1 (555) 047-9921",
    department: "Finance",
    jobTitle: "Financial Analyst",
    employmentType: "Full-time",
    reportingManager: "CFO",
    workLocation: "Austin Office",
    status: "Active",
    dateOfJoining: "2023-03-01",
    contractStart: "2023-03-01",
    contractEnd: "",
    probationEnd: "2023-06-01",
    salary: "$105,000",
    band: "L4",
    grade: "Mid",
    role: "Analyst",
  },
  {
    id: "EMP010",
    firstName: "Nina",
    lastName: "Osei",
    email: "nina.osei@staffhub.io",
    phone: "+1 (555) 158-3310",
    department: "Engineering",
    jobTitle: "DevOps Engineer",
    employmentType: "Full-time",
    reportingManager: "James Kim",
    workLocation: "Remote",
    status: "Terminated",
    dateOfJoining: "2021-05-10",
    contractStart: "2021-05-10",
    contractEnd: "2023-11-30",
    probationEnd: "2021-08-10",
    salary: "$125,000",
    band: "L4",
    grade: "Mid",
    role: "Developer",
  },
];

const employeeSlice = createSlice({
  name: "employee",
  initialState: {
    list: INITIAL_EMPLOYEES,
    loading: true,          
    searchQuery: "",
    filterStatus: "All",
    filterDept: "All",
    selectedId: null,
    modalMode: null,
  },
  reducers: {
    setLoading(state, { payload }) {
      state.loading = payload;
    },
    addEmployee(state, { payload }) {
      state.list.push(payload);
    },
    updateEmployee(state, { payload }) {
      const idx = state.list.findIndex((e) => e.id === payload.id);
      if (idx !== -1) state.list[idx] = payload;
    },
    deleteEmployee(state, { payload }) {
      state.list = state.list.filter((e) => e.id !== payload);
    },
    setSearchQuery(state, { payload }) {
      state.searchQuery = payload;
    },
    setFilterStatus(state, { payload }) {
      state.filterStatus = payload;
    },
    setFilterDept(state, { payload }) {
      state.filterDept = payload;
    },
    setSelectedId(state, { payload }) {
      state.selectedId = payload;
    },
    setModalMode(state, { payload }) {
      state.modalMode = payload;
    },
    openAddModal(state) {
      state.selectedId = null;
      state.modalMode = "add";
    },
    openEditModal(state, { payload }) {
      state.selectedId = payload;
      state.modalMode = "edit";
    },
    closeModal(state) {
      state.modalMode = null;
      state.selectedId = null;
    },
  },
});

export const {
  setLoading,
  addEmployee,
  updateEmployee,
  deleteEmployee,
  setSearchQuery,
  setFilterStatus,
  setFilterDept,
  setSelectedId,
  setModalMode,
  openAddModal,
  openEditModal,
  closeModal,
} = employeeSlice.actions;

export default employeeSlice.reducer;